using AccountsReceivable.API.Data;
using AccountsReceivable.API.Models;
using AccountsReceivable.API.Models.RequestModel;
using AccountsReceivable.API.Services.Interface;
using AutoMapper;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountsReceivable.API.Services
{
    public class UpdateCashBackService : IUpdateCashBackService
    {
        private readonly AccountReceivableDataContext _context;
        private readonly IMapper _mapper;
        public UpdateCashBackService(AccountReceivableDataContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public async Task<CashbackMasterRequest> AddCashBackForCustomer(CashbackMasterRequest dto)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (dto != null)
                    {
                        if (dto.CustomerId != null)
                        {
                            CashBackMasters CashBackMaster = new CashBackMasters();
                            CustomerWallet CustomerWallet = await _context.CustomerWallet.FirstOrDefaultAsync(x => x.CustomerId == dto.CustomerId);
                            if (CustomerWallet.TotalBusinessAmount > 1000)
                            {
                                CashBackMaster.CashbackValue = CustomerWallet.TotalBusinessAmount * dto.CashBackPercentage / 100;
                                CashBackMaster.MinimumBusinessAmount = CustomerWallet.TotalBusinessAmount;
                                CashBackMaster.MaximumCashbackAmount = 50;
                                CashBackMaster.IsPercentage = dto.CashBackPercentage;
                                CashBackMaster.CustomerId = dto.CustomerId;
                                CashBackMaster.IsActive = true;
                                _context.CashBackMaster.Add(CashBackMaster);
                                //_context.Entry(CashBackMaster).CurrentValues.SetValues(dto);
                            }
                            else
                            {
                                throw new Exception("Your Bussiness Amount less than 1000");
                            }
                            // }
                            //else
                            //{
                            //    throw new Exception("Please Select Customer");
                            //}
                            int id = await _context.SaveChangesAsync();
                            if (id > 0)
                            {
                                CashBackTransaction cashbackTrans = await _context.CashBackTransaction.FirstOrDefaultAsync(x => x.CustomerId == dto.CustomerId);
                                CashBackTransaction cashbacktransaction = new CashBackTransaction();
                                if (cashbackTrans == null)
                                {
                                    cashbacktransaction.CustomerId = dto.CustomerId;
                                    cashbacktransaction.AutogeneratedCashVackValue = CustomerWallet.TotalBusinessAmount * dto.CashBackPercentage / 100;
                                    cashbacktransaction.ActualCashbackValue = CustomerWallet.TotalBusinessAmount * dto.CashBackPercentage / 100;
                                    cashbacktransaction.AppliedDateTime = DateTime.UtcNow;
                                    cashbacktransaction.IsActive = true;
                                    _context.CashBackTransaction.Add(cashbacktransaction);
                                }
                                else
                                {
                                    _context.Entry(cashbackTrans).CurrentValues.SetValues(dto);
                                }
                                await _context.SaveChangesAsync();
                                //CustomerWallet CustomerWalletOld = await _context.CustomerWallet.FirstOrDefaultAsync(x => x.CustomerId == dto.CustomerId);
                                if (CustomerWallet != null)
                                {
                                    CustomerWallet CustomerWalletOld = new CustomerWallet();
                                    CustomerWalletOld.CreditLimit = CustomerWallet.CreditLimit + CustomerWallet.TotalBusinessAmount * dto.CashBackPercentage / 100;
                                   // CustomerWallet.CreditLimit = CustomerWalletOld.CreditLimit;
                                    CustomerWalletOld.CustomerWalletId = CustomerWallet.CustomerWalletId;
                                    CustomerWalletOld.TotalBusinessAmount = CustomerWallet.TotalBusinessAmount;
                                    CustomerWalletOld.TotalPaidAmount = CustomerWallet.TotalPaidAmount;
                                    CustomerWalletOld.DueAmount = CustomerWallet.DueAmount;
                                    CustomerWalletOld.CreatedBy = CustomerWallet.CreatedBy;
                                    CustomerWalletOld.CreatedDate = CustomerWallet.CreatedDate;
                                    CustomerWalletOld.ModifiedBy = CustomerWallet.ModifiedBy;
                                    CustomerWalletOld.ModifiedDate = CustomerWallet.ModifiedDate;
                                    _context.Entry(CustomerWallet).CurrentValues.SetValues(CustomerWalletOld);
                                    await _context.SaveChangesAsync();
                                    CustomerWalletTransaction customerWalletTransaction = new CustomerWalletTransaction();
                                    customerWalletTransaction.CustomerWalletId = CustomerWallet.CustomerWalletId;
                                    customerWalletTransaction.TransactionAmount = CustomerWallet.TotalBusinessAmount * dto.CashBackPercentage / 100;
                                    customerWalletTransaction.TransactionType = "CashbackDeposit";
                                    customerWalletTransaction.TransactionModeId = 4;
                                    customerWalletTransaction.CustomerId = dto.CustomerId;
                                    _context.CustomerWalletTransaction.Add(customerWalletTransaction);
                                    await _context.SaveChangesAsync();
                                    CustomerWalletTransactionDetail CustoWalleTransacDetail = new CustomerWalletTransactionDetail();
                                    CustoWalleTransacDetail.CustomerWalletTransactionId = customerWalletTransaction.CustomerWalletTransactionId;
                                    CustoWalleTransacDetail.ReferenceTable = "CashbackTransaction";
                                    CustoWalleTransacDetail.ReferenceId = cashbacktransaction.CashBackTransactionId.ToString();
                                    CustoWalleTransacDetail.Amount = CustomerWallet.TotalBusinessAmount * dto.CashBackPercentage / 100;
                                    CustoWalleTransacDetail.CustomerId = dto.CustomerId;
                                    _context.CustomerWalletTransactionDetail.Add(CustoWalleTransacDetail);
                                    await _context.SaveChangesAsync();
                                    //await transaction.CommitAsync();
                                    //_context.Entry(customerWalletTransDetail).CurrentValues.SetValues(CustoWalleTransacDetail);

                                    //_context.Entry(customerWalletTrans).CurrentValues.SetValues(customerWalletTransaction);

                                }
                                else
                                {
                                    throw new Exception("Invalid request.");
                                }
                            }
                            await transaction.CommitAsync();
                            return dto;
                        }
                    }
                    return dto;
                }
                catch (Exception ex)
                {
                    await transaction.RollbackAsync();
                    throw new Exception("Invalid request.");
                }
            }
        }
    }
}
