using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountsReceivable.API.ViewModels
{
    public class CashBackTransactionVM
    {
        public int CashBackTransactionId { get; set; }
        public int? CustomerId { get; set; }
        public int? AutogeneratedCashVackValue { get; set; }
        public int? ActualCashbackValue { get; set; }
        public DateTime? AppliedDateTime { get; set; }
        public Boolean IsActive { get; set; }
    }
}
