using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountsReceivable.API.Models.RequestModel
{
    public class RequestCreateCustomerCashBack
    {
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public List<CustomerCashBackDtl> CustomerDtlList { get; set; }
    }
    public class CustomerCashBackDtl
    {
        public int CustomerId { get; set; }
        public int? TotalAmount { get; set; }
        public int? MinimumBusinessAmount { get; set; }
        public int? MaximumCashbackAmount { get; set; }
        public int? ActualCashbackValue { get; set; }
        public int? AutogeneratedCashVackValue { get; set; }
        public bool IsPercentage { get; set; }
        public int? CashbackValue { get; set; }
        public bool IsInCashback { get; set; }
    }
}
