using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AccountsReceivable.API.Models
{
    [Table("CashBackTransaction")]
    public class CashBackTransaction
    {
        [Key]
        public int CashBackTransactionId { get; set; }
        public int CustomerId { get; set; }
        public decimal AutogeneratedCashVackValue { get; set; }
        public decimal ActualCashbackValue { get; set; }
        public DateTime AppliedDateTime { get; set; }
        public bool IsActive { get; set; }
    }
}
