using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountsReceivable.API.Models
{
    public class GetCustomerCashBackList
    {
        [Key]
        public int CustomerId { get; set; }
        public int? TotalAmount { get; set; }
        public int? MinimumBusinessAmount { get; set; }
        public int? MaximumCashbackAmount { get; set; }
        public int? ActualCashbackValue { get; set; }
        public int? AutogeneratedCashVackValue { get; set; }
        public bool? IsPercentage { get; set; }
        public int? CashbackValue { get; set; }
        public bool? IsInCashback { get; set; }
    }
}
