using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountsReceivable.API.Models
{
    public class GetCustomerCashBackList
    {
        [Key]
        public Guid Id { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? MinimumBusinessAmount { get; set; }
        public decimal? MaximumCashbackAmount { get; set; }
        public decimal? ActualCashbackValue { get; set; }
        public decimal? AutogeneratedCashVackValue { get; set; }
        public bool? IsPercentage { get; set; }
        public decimal? CashbackValue { get; set; }
        public bool? IsInCashback { get; set; }
    }
}
